// Decompiled with JetBrains decompiler
// Type: DistantWorlds.Types.RaceVictoryConditionType
// Assembly: DistantWorlds.Types, Version=1.9.5.12, Culture=neutral, PublicKeyToken=null
// MVID: C87DBA0E-BD3A-46BA-A8F0-EE9F5E5721E2
// Assembly location: H:\7\DistantWorlds.Types.dll

using System;

namespace DistantWorlds.Types
{
  [Serializable]
  public enum RaceVictoryConditionType : byte
  {
    Undefined,
    ControlHomeworld,
    ControlPlanetTypePercentage,
    ControlLargestColoniesByType,
    ControlMostRuins,
    PopulationHighest,
    PopulationHappiest,
    MostHomeworlds,
    OwnLargestCapitalShip,
    MostSpaceports,
    MostMiningStations,
    MostResortBases,
    DestroyMostShips,
    DestroyMostTroops,
    DestroyMoreShipsThanLoseTimesFactor,
    DestroyMoreEnemyTroopsThanLoseTimesFactor,
    DestroyMostCreaturesByType,
    LoseFewestShips,
    LoseFewestTroops,
    MostIntelligenceMissionsSucceed,
    MostIntelligenceMissionsIntercepted,
    ConquerMostEnemyColonies,
    ExterminateOrEnslaveMostPopulation,
    EnslavePopulationProportionEmpire,
    BuildWonder,
    KeepLeaderAlive,
    MostScientists,
    MostExperiencedAdmiral,
    MostExperiencedGeneral,
    ResearchLeastAdvanced,
    ResearchMostAdvanced,
    ResearchMostCompletedBranches,
    ResearchMostCompletedBranchesByIndustry,
    HighestTradeVolume,
    MostTourismIncome,
    MostTradeIncome,
    HighestPrivateRevenue,
    ControlRestrictedResourceSupply,
    LargestMilitary,
    LargestMilitaryNonAllied,
    MostTroops,
    MostTroopsNonAllied,
    MutualDefensePactsFormedProportionAllEmpires,
    FreeTradeAgreementsFormedProportionAllEmpires,
    LeastWarsStarted,
    LeastBrokenTreaties,
    LeastTreaties,
    MostTimeWarring,
    LeastTimeWarring,
    MostSubjugatedDominions,
    OldestMutualDefensePact,
    OldestFreeTradeAgreement,
    ExploreMostSystems,
    ExploreGalaxyPercentage,
    MineMostResourcesLuxury,
    MineMostResourcesStrategic,
    BuildMostMilitaryShips,
    BuildMostCivilianShips,
    BuildMostBases,
    CaptureMostShips,
    PirateBuildMostHiddenBases,
    PirateBuildHiddenFortress,
    PirateControlColoniesPercentage,
    PirateEliminateMostPirateFactions,
    PirateMostSuccessfulMissionsAttack,
    PirateMostSuccessfulMissionsDefend,
    PirateMostSmugglingIncome,
    PirateMostProtectionIncome,
    PirateMostSuccessfulRaids,
    PirateBuildCriminalNetwork,
    MineMostResourcesColonyManufactured,
  }
}
